FROM python:3

RUN apt-get update
RUN python3 -m pip install --upgrade pip
RUN pip3 install --upgrade pika redis jsonpickle requests Pillow numpy requests 

WORKDIR /srv
COPY worker-server.py drop-redis.py redis-list.py /srv/
CMD [ "python3", "worker-server.py"]