##
## You provide this
##
## copy from  kubernetes-tutorial 05-guestbook
## change names/ environment variable
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: tfserving-deployment
spec:
  selector:
    matchLabels:
      app: tfserving
  replicas: 1
  template:
    metadata:
      labels:
        app: tfserving
    spec:
      containers:
      - name: tfserving
        image: shollatz/vgg16_diff-nodiff_classifier:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: REDIS_HOST
          value: redis
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: TFSERVING_HOST
          value: tfserving
