##
## You provide this
##
FROM python:3

RUN pip3 install --upgrade pika redis jsonpickle requests flask Pillow

WORKDIR /srv
COPY rest-server.py /srv
ENV FLASK_APP=rest-server.py
## ENV REDIS_HOST=redis
## ENV RABBITMQ_HOST=rabbitmq

ENV FLASK_PORT 5000

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

CMD [ "python3", "rest-server.py"]

