##
## You provide this
##
FROM python:3

RUN apt-get update
RUN pip3 install --upgrade pika

WORKDIR /srv
COPY logs.py /srv

## ENV REDIS_HOST=redis
##  ENV RABBITMQ_HOST=rabbitmq

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

CMD [ "python3", "logs.py"]